<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbf604c38efe92fc949405b4b493bfd5b
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbf604c38efe92fc949405b4b493bfd5b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbf604c38efe92fc949405b4b493bfd5b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbf604c38efe92fc949405b4b493bfd5b::$classMap;

        }, null, ClassLoader::class);
    }
}
